version: 9.2.1
validate: false
instance_dir: tmp/solr
download_dir: tmp/solr

# Place any default configuration for solr_wrapper here
port: <%= ENV['SOLR_URL'] %>
collection:
  dir: solr/conf/
  name: blacklight-core
