# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

# ArcGIS Online Base URL
ARCGIS_BASE_URL: 'https://www.arcgis.com/home/webmap/viewer.html'

# Download path can be configured using this setting
#DOWNLOAD_PATH: "./tmp/cache/downloads"

# DEPRECATED Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# The bq boost value for spatial search matches within a bounding box
BBOX_WITHIN_BOOST: '10'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '2'

# Homepage Map Geometry
# Leave null to default to entire world
# Add a stringified GeoJSON object to scope initial render (example from UMass)
# HOMEPAGE_MAP_GEOM: null
HOMEPAGE_MAP_GEOM: '{"type":"Polygon","coordinates":[[[-73.747,43.0045],[-73.747,41.1143],[-69.7787,41.1143],[-69.7787,43.0045]]]}'

# Non-search-field GeoBlacklight application permitted params
GBL_PARAMS:
  - :bbox
  - :email
  - :file
  - :format
  - :id
  - :logo
  - :provider
  - :type
  - :BBOX
  - :HEIGHT
  - :LAYERS
  - :QUERY_LAYERS
  - :URL
  - :WIDTH
  - :X
  - :Y

# Solr field mappings
FIELDS:
  :ACCESS_RIGHTS: 'dct_accessRights_s'
  :ALTERNATIVE_TITLE: 'dct_alternative_sm'
  :CENTROID: 'dcat_centroid_ss'
  :CREATOR: 'dct_creator_sm'
  :DATE_ISSUED: 'dct_issued_s'
  :DATE_RANGE: 'gbl_dateRange_drsim'
  :DESCRIPTION: 'dct_description_sm'
  :FORMAT: 'dct_format_s'
  :FILE_SIZE: 'gbl_fileSize_s'
  :GEOREFERENCED: 'gbl_georeferenced_b'
  :ID: 'id'
  :IDENTIFIER: 'dct_identifier_sm'
  :INDEX_YEAR: 'gbl_indexYear_im'
  :IS_PART_OF: 'dct_isPartOf_sm'
  :IS_REPLACED_BY: 'dct_isReplacedBy_sm'
  :ISO_TOPIC_CATEGORY: 'dcat_theme_sm'
  :KEYWORD: 'dcat_keyword_sm'
  :LANGUAGE: 'dct_language_sm'
  :LICENSE: 'dct_license_sm'
  :MEMBER_OF: 'pcdm_memberOf_sm'
  :METADATA_VERSION: 'gbl_mdVersion_s'
  :MODIFIED: 'gbl_mdModified_dt'
  :OVERLAP_FIELD: 'solr_bboxtype'
  :PUBLISHER: 'dct_publisher_sm'
  :PROVIDER: 'schema_provider_s'
  :REFERENCES: 'dct_references_s'
  :RELATION: 'dct_relation_sm'
  :REPLACES: 'dct_replaces_sm'
  :RESOURCE_CLASS: 'gbl_resourceClass_sm'
  :RESOURCE_TYPE: 'gbl_resourceType_sm'
  :RIGHTS: 'dct_rights_sm'
  :RIGHTS_HOLDER: 'dct_rightsHolder_sm'
  :SOURCE: 'dct_source_sm'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :GEOMETRY: 'locn_geometry'
  :SUBJECT: 'dct_subject_sm'
  :SUPPRESSED: 'gbl_suppressed_b'
  :TEMPORAL_COVERAGE: 'dct_temporal_sm'
  :TITLE: 'dct_title_s'
  :VERSION: 'dct_isVersionOf_sm'
  :WXS_IDENTIFIER: 'gbl_wxsIdentifier_s'
  :ANNOTATION: 'umass_annotated_s'


# Institution deployed at
INSTITUTION: 'UMass Amherst'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'mods'
  - 'fgdc'
  - 'iso19139'
  - 'html'

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Use the geometry type for the data relations icon
USE_GEOM_FOR_RELATIONS_ICON: false

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'tms'
  - 'wfs'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

# WMS Parameters
WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
    DETECT_RETINA: true
    INDEX:
      DEFAULT: &default
        color: "#1eb300"
        weight: "1"
        radius: "4"
      UNAVAILABLE:
        <<: *default
        color: "#b3001e"
      SELECTED:
        <<: *default
        color: "#006bde"
  VIEWERS:
    WMS:
      <<: *opacity_control
    TILEDMAPLAYER:
      <<: *opacity_control
    FEATURELAYER:
      <<: *opacity_control
    DYNAMICMAPLAYER:
      <<: *opacity_control
    IMAGEMAPLAYER:
      <<: *opacity_control

# Toggle the help text feature that offers users context
HELP_TEXT:
  viewer_protocol:
      - 'dynamic_map_layer'
      - 'feature_layer'
      - 'iiif'
      - 'iiif_manifest'
      - 'image_map_layer'
      - 'index_map'
      - 'tiled_map_layer'
      - 'wms'
      - 'tms'
      - 'oembed'
